Set input text length to 16
phasehq/console pull request #186
Opened 2024-02-18 18:33 UTC by teyim

# Description 📣

Reduce input text length to 16 characters

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️
Manual test

```sh
# Here's some code block to paste some code snippets
```

2024-02-19 14:07 UTC, rohan-chaturvedi commented
@teyim is this ready for review?

2024-02-19 16:31 UTC, teyim commented
yes @rohan-chaturvedi

2024-02-20 06:42 UTC, rohan-chaturvedi requested changes
This looks good! Lets just make the max length 32, to allow for more descriptive names.

2024-02-20 06:42 UTC, rohan-chaturvedi commented on frontend/components/apps/NewAppDialog.tsx
> +                              maxLength={16}
```suggestion
                              maxLength={32}
```

2024-02-20 06:42 UTC, rohan-chaturvedi commented on frontend/components/onboarding/TeamName.tsx
> +        maxLength={16}
```suggestion
        maxLength={32}
```

2024-02-20 08:10 UTC, teyim commented on frontend/components/apps/NewAppDialog.tsx
> +                              maxLength={16}
ok, i will update that

2024-02-21 10:40 UTC, teyim commented
Hi @rohan-chaturvedi , i have modified this by creating a global constant to hold the max input string length..i think this approach is better.. please review

2024-02-21 12:56 UTC, rohan-chaturvedi requested changes
@teyim Thanks for this. Not 100% sure this solution will work for all use cases, as input field max-length can vary depending on the context, but lets try this solution and see how much we can standardize it.

Just requesting a couple of fixes. Lets go ahead with this.

2024-02-21 12:56 UTC, rohan-chaturvedi commented on frontend/components/apps/NewAppDialog.tsx
> +import { MAX_INPUT_STRING_LENGTH, MAX_STRING_LENGTH } from '@/constants'
```suggestion
import { MAX_INPUT_STRING_LENGTH } from '@/constants'
```

I think only one import is required here

2024-02-21 12:56 UTC, rohan-chaturvedi commented on frontend/constants/index.ts
> +export const MAX_INPUT_STRING_LENGTH=32
```suggestion
export const MAX_INPUT_STRING_LENGTH=32

```

Adding a newline at EOF

2024-02-21 13:21 UTC, rohan-chaturvedi approved these changes

2024-02-21 13:24 UTC, merged