Remove user / application limits on self-hosted
phasehq/console pull request #226
Opened 2024-04-07 09:59 UTC by nimish-ks

## :mag: Overview

*Provide a brief overview of the context and the problem your pull request aims to solve. Include any relevant background information to help reviewers understand the current situation.*

## :bulb: Proposed Changes

*Detail the proposed changes, including new features, bug fixes, or improvements. Explain how these changes impact the project, including any internal structure alterations or refactorings.*

## :framed_picture: Screenshots or Demo

*Include before and after screenshots or animated GIFs/demo links to illustrate the changes visually. This is especially useful for UI/UX improvements.*

## :memo: Release Notes

*Summarize the changes in a user-friendly manner. Highlight new features, bug fixes, and any breaking changes, including migration steps or deprecated functionalities.*

## :question: Open Questions

*If there are aspects of the changes that you're unsure about or would like feedback on, list them here.*

### :test_tube: Testing

*Describe the testing strategy. List new tests added, existing tests modified, and any testing gaps.*

### :dart: Reviewer Focus

*Guide the reviewer on where to start the review process. Suggest specific files, modules, or functionalities to focus on as entry points.*

### :heavy_plus_sign: Additional Context

*Provide any additional information that might be helpful for reviewers and future contributors, such as links to related issues, discussions, or resources.*

## :sparkles: How to Test the Changes Locally

*Give clear instructions on how to test the changes locally, including setting up the environment, any necessary commands, or external dependencies.*

### :green_heart: Did You...

- [ ] Ensure linting passes (code style checks)?
- [ ] Update dependencies and lockfiles (if required)
- [ ] Verify the app builds locally?
- [ ] Manually test the changes on different browsers/devices?

2024-04-07 12:17 UTC, nimish-ks commented
@rohan-chaturvedi getting `ApolloError: An active invitiation already exists for this user.` on self-hosted in spite of the user being invited the first time.

![image](https://github.com/phasehq/console/assets/85357445/24d6f050-5589-4fb2-b04a-17543aa486f7)

2024-04-09 05:01 UTC, rohan-chaturvedi commented
> @rohan-chaturvedi getting `ApolloError: An active invitiation already exists for this user.` on self-hosted in spite of the user being invited the first time.
> 
> ![image](https://private-user-images.githubusercontent.com/85357445/320280266-24d6f050-5589-4fb2-b04a-17543aa486f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzgwMzcsIm5iZiI6MTcxMjYzNzczNywicGF0aCI6Ii84NTM1NzQ0NS8zMjAyODAyNjYtMjRkNmYwNTAtNTU4OS00ZmIyLWIwNGEtMTc1NDNhYTQ4NmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA0NDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZDUwMDVmN2JhNWE0OGZlOWE2ZDRkNmIxNDM3MjYyNmI0MTVmZDUzZWJhNTdiMjVhOTc1ZjFkZDg3MzI3YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ampvWA6MJfPh3ow9OKIkWa60hmTw1F7TSwId5ozwBCk)

@nimish-ks  This was a UI issue: there was no loading or disabled state on the "Invite" button, so accidental double clicks were triggering duplicate invites. I've fixed this by adding a loading state to the button, as well as a fix to reset the error message alert when closing the dialog.

2024-04-09 07:10 UTC, rohan-chaturvedi requested changes
LGTM, just suggesting a more concise definition of `PLAN_CONFIG`

2024-04-09 07:11 UTC, rohan-chaturvedi requested changes

2024-04-09 07:11 UTC, rohan-chaturvedi commented on backend/backend/quotas.py
> +    }
```suggestion
PLAN_CONFIG = {
    "FR": {
        "name": "Free",
        "max_users": 5 if CLOUD_HOSTED else None,
        "max_apps": 3 if CLOUD_HOSTED else None,
        "max_envs_per_app": 3,
    },
    "PR": {
        "name": "Pro",
        "max_users": None,
        "max_apps": None,
        "max_envs_per_app": 10,
    },
    "EN": {
        "name": "Enterprise",
        "max_users": None,
        "max_apps": None,
        "max_envs_per_app": None,
    },
}
```

2024-04-09 07:15 UTC, rohan-chaturvedi approved these changes

2024-04-09 07:16 UTC, merged