Secret changes dialog added #274
phasehq/console pull request #318
Opened 2024-07-31 14:18 UTC by harshith-1008

## :mag: Overview

- This pull request solves issue #274.  
- Feature: Functionality which allows user to see the changes made to environment secrets. 

## :bulb: Proposed Changes

- Used GenericDialog component to show the changes made by user
- Added info button which onClick shows dialog 
- Created type SecretChange for the secret changes
- Created a component DisplayChanges which returns changes of a particular secret
- Also limited key value to 50 characters so that it does overflow out of the dialogue

## :framed_picture: Screenshots or Demo

Before
<img width="1470" alt="Screenshot 2024-07-31 at 6 53 37 PM" src="https://github.com/user-attachments/assets/ce5635ea-c1db-4586-a78e-1f2aa0d2598e">

After
<img width="1470" alt="Screenshot 2024-07-31 at 7 34 42 PM" src="https://github.com/user-attachments/assets/f722e390-67f1-42ef-8ab7-e6abf17df673">
<img width="1470" alt="Screenshot 2024-07-31 at 7 34 55 PM" src="https://github.com/user-attachments/assets/1e94a196-0745-42d9-bcde-092ee66f6775">

## :memo: Release Notes

User now can see the changes made to the environment secrets

## :question: Open Questions

Is there anyway I can enhance the UI more? 

### :test_tube: Testing

- Add a secret
- Change an attribute of a pre-existing secret
- Remove a tag from the secret and add other tags  

### :dart: Reviewer Focus

You can just make any desired changes and click on the info button to view the changes 

### :heavy_plus_sign: Additional Context

issue #274 

## :sparkles: How to Test the Changes Locally

- Pull the branch
- log in to your phase console account 
- head over to an environment of any app and start testing

### :green_heart: Did You...

- [x] Ensure linting passes (code style checks)?
- [ ] Update dependencies and lockfiles (if required)
- [ ] Regenerate graphql schema and types (if required)
- [ ] Verify the app builds locally?
- [x] Manually test the changes on different browsers/devices?

2024-08-01 07:51 UTC, harshith-1008 commented
@rohan-chaturvedi 
If possible, could you please look into this pr?

2024-08-09 15:43 UTC, rohan-chaturvedi commented
@harshith-1008 Could you fix the filename please? 
![image](https://github.com/user-attachments/assets/676d4cc0-3f31-4c73-bde7-c1e69d9c707a)

2024-08-11 14:48 UTC, harshith-1008 commented
> @harshith-1008 Could you fix the filename please? ![image](https://private-user-images.githubusercontent.com/6710327/356669720-676d4cc0-3f31-4c73-bde7-c1e69d9c707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODc4ODMsIm5iZiI6MTcyMzM4NzU4MywicGF0aCI6Ii82NzEwMzI3LzM1NjY2OTcyMC02NzZkNGNjMC0zZjMxLTRjNzMtYmRlNy1jMWU2OWQ5YzcwN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTQ0NjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ5YzNkZGEzY2JjZDQ5MDEyZTgyZDI2MzRhNzY2OTU3YmI0NTVlNzk5MTc3MmRkNTUyZDhlZDVkY2Q1YWFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PYTgM9cExZ8NwwxJWID4QUlhWqRuSrpxHu6ajxaKX6Q)

<img width="1470" alt="Screenshot 2024-08-11 at 8 10 21 PM" src="https://github.com/user-attachments/assets/7e0e1dec-cf11-4d62-aa63-ec73adfc5c91">

@rohan-chaturvedi for some reason vscode isnt allowing me to keep this license file because folder name license already exists, can you please guide me to restore it?

2024-08-11 15:02 UTC, rohan-chaturvedi commented
> > @harshith-1008 Could you fix the filename please? ![image](https://private-user-images.githubusercontent.com/6710327/356669720-676d4cc0-3f31-4c73-bde7-c1e69d9c707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODc4ODMsIm5iZiI6MTcyMzM4NzU4MywicGF0aCI6Ii82NzEwMzI3LzM1NjY2OTcyMC02NzZkNGNjMC0zZjMxLTRjNzMtYmRlNy1jMWU2OWQ5YzcwN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTQ0NjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ5YzNkZGEzY2JjZDQ5MDEyZTgyZDI2MzRhNzY2OTU3YmI0NTVlNzk5MTc3MmRkNTUyZDhlZDVkY2Q1YWFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PYTgM9cExZ8NwwxJWID4QUlhWqRuSrpxHu6ajxaKX6Q)
> 
> <img alt="Screenshot 2024-08-11 at 8 10 21 PM" width="1470" src="https://private-user-images.githubusercontent.com/123820448/356885790-7e0e1dec-cf11-4d62-aa63-ec73adfc5c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODgzNDcsIm5iZiI6MTcyMzM4ODA0NywicGF0aCI6Ii8xMjM4MjA0NDgvMzU2ODg1NzkwLTdlMGUxZGVjLWNmMTEtNGQ2Mi1hYTYzLWVjNzNhZGZjNWM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNDU0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzEwMWJiNTY3ODQxZjY0ZWRkMTZiNDkwNjI2OTdkN2ZkMjc4NGM3NzFhYzQxNzYxNDJhZWY3YzM1ZWRiNTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2DNkmrYJu4aVVbFFhDti_b4Sw3Na795acec0F9oR7Ro">
> @rohan-chaturvedi for some reason vscode isnt allowing me to keep this license file because folder name license already exists, can you please guide me to restore it?

Thanks a lot for the screenshot! Now I understand why this was a problem 😅 

I'll raise a PR to rename the license folder in a bit, that should resolve it.

2024-08-12 14:17 UTC, rohan-chaturvedi commented
Hey @harshith-1008 , a couple of updates:
1) We've updated the UX for deleting secrets. Secrets can now be "staged" for delete, and are only deleted when clicking on "Deploy". See the PR for a full demo: https://github.com/phasehq/console/pull/340
This means we need to add Deleted secrets to the changed secrets dialog

2) I was working on a cleaner design for this dialog for while. I've made a [Figma mock here](https://www.figma.com/design/XGgL1d2uMi9PvbUKb2Ka2m/Undeployed-changed---detail-dialog?node-id=0-1&t=FDdZcgoFpbNyzNDi-1).

Here's a screenshot as well:
![Frame 1(1)](https://github.com/user-attachments/assets/050c573f-2d0e-4091-b78e-b766b0af3ab2)

You can grab the colors from Figma. The tailwind colors are:
- Dialog title: `text-zinc-900 dark:text-zinc-900`
- Dialog subtitle: `text-zinc-500`
- Created: `text-emerald-400` (Backgrounds: `bg-emerald-400/20 dark:bg-emerald-400/10`)
- Updated: `text-amber-400 ` (Backgrounds: `bg-amber-400/20 dark:bg-amber-400/10`)
- Deleted: `text-red-400` (Backgrounds: `bg-red-400/20 dark:bg-red-400/10`)

Sorry for the constant design updates! Lmk if you have any questions, we can hop on a slack huddle and discuss it as well.

2024-08-15 11:05 UTC, harshith-1008 commented
<img width="1470" alt="Screenshot 2024-08-15 at 4 29 31 PM" src="https://github.com/user-attachments/assets/16cc3d5d-94d5-410d-bcf4-d128e4254f82">

@rohan-chaturvedi I tried changing the UI, Can you guide me how to override text-color of tags? In Tag component the styling is (text-zinc-700 dark:text-zinc-200).

<img width="997" alt="Screenshot 2024-08-15 at 4 31 44 PM" src="https://github.com/user-attachments/assets/04272f89-7ac5-4e1a-8e80-5e809e3b3043">

I tried this method but it isn't working. and should I decrease the height and width of tags?

2024-08-15 13:06 UTC, rohan-chaturvedi commented
> <img alt="Screenshot 2024-08-15 at 4 29 31 PM" width="1470" src="https://private-user-images.githubusercontent.com/123820448/358200213-16cc3d5d-94d5-410d-bcf4-d128e4254f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjcyODYsIm5iZiI6MTcyMzcyNjk4NiwicGF0aCI6Ii8xMjM4MjA0NDgvMzU4MjAwMjEzLTE2Y2MzZDVkLTk0ZDUtNDEwZC1iY2Y0LWQxMjhlNDI1NGY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMzAzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTg2YTBjNGJlYTdiNTBlY2M0ZTc4ZmNjMWE5ZGIyNjc4MTM5OGM3N2M0NzdmZTkzMGYzYjhhOWJjYjE5ZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._9CutswYBhKXGvuq8SLolnNs-VhXn_09bqbgiLlsiJg">
> 
> @rohan-chaturvedi I tried changing the UI, Can you guide me how to override text-color of tags? In Tag component the styling is (text-zinc-700 dark:text-zinc-200).
> <img alt="Screenshot 2024-08-15 at 4 31 44 PM" width="997" src="https://private-user-images.githubusercontent.com/123820448/358200689-04272f89-7ac5-4e1a-8e80-5e809e3b3043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjcyODYsIm5iZiI6MTcyMzcyNjk4NiwicGF0aCI6Ii8xMjM4MjA0NDgvMzU4MjAwNjg5LTA0MjcyZjg5LTdhYzUtNGUxYS04ZTgwLTVlODA5ZTNiMzA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMzAzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDVlZDU5ODUxN2I1NTM0N2M5YmMxYmJhNWZkZDkxMzE5ZDk0NzQ0YTVmZTgxMjZiYjE4YTFkNWIyMzY2MDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JjzNQV0VsKi3TduTiaY_FuNcyzLVeTGKfNNKjW68p6k">
> 
> I tried this method but it isn't working. and should I decrease the height and width of tags?

@harshith-1008 You could add a `variant` prop to the Tag component that takes a string of type: `'normal' | 'deleted' | 'created'`. Apply the styles based on the value of this prop. Check out the Button component to see how a variant can be added. Make the `'normal'` default value of the prop, so that you won't have to add this prop wherever the Tag is currently used. 

Lets keep the height and width of the tags for now.

2024-08-16 05:13 UTC, harshith-1008 commented
@rohan-chaturvedi can you look into these changes? I have kept the tags width and height same. 

<img width="1470" alt="Screenshot 2024-08-16 at 10 41 51 AM" src="https://github.com/user-attachments/assets/d0242a24-aec0-40f0-a1bc-3dd2018791ec">

2024-08-16 05:52 UTC, rohan-chaturvedi commented
> @rohan-chaturvedi can you look into these changes? I have kept the tags width and height same.
> 
> <img alt="Screenshot 2024-08-16 at 10 41 51 AM" width="1470" src="https://private-user-images.githubusercontent.com/123820448/358474231-d0242a24-aec0-40f0-a1bc-3dd2018791ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODc3MTUsIm5iZiI6MTcyMzc4NzQxNSwicGF0aCI6Ii8xMjM4MjA0NDgvMzU4NDc0MjMxLWQwMjQyYTI0LWFlYzAtNDBmMC1hMWJjLTNkZDIwMTg3OTFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNTUwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWFkNmI4NzQ5OTQyNDg4NzE2YjBkZjE4NzZhZmY2YTc3YWIzMjdiM2IzNjJmYmI0YmJiODA0YzQ1MmY4Zjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MOoCf76nkoDCEmyG59E38YnJOvJkkDd3jsgarIcMX8E">

Looking good! Only issue I can see is that monospace font isn't used in the right places. Could you take a look at that?

2024-08-16 10:16 UTC, harshith-1008 commented
<img width="1470" alt="Screenshot 2024-08-16 at 3 45 32 PM" src="https://github.com/user-attachments/assets/93c0d1e8-8556-4c2f-9c3c-631d8e3ccc6b">

@rohan-chaturvedi  changed font irregularities.

2024-08-16 10:21 UTC, rohan-chaturvedi commented
> <img alt="Screenshot 2024-08-16 at 3 45 32 PM" width="1470" src="https://private-user-images.githubusercontent.com/123820448/358550363-93c0d1e8-8556-4c2f-9c3c-631d8e3ccc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM4NjIsIm5iZiI6MTcyMzgwMzU2MiwicGF0aCI6Ii8xMjM4MjA0NDgvMzU4NTUwMzYzLTkzYzBkMWU4LTg1NTYtNGMyZi05YzNjLTYzMWQ4ZTNjY2M2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMDE5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTMwMzU1MDg2NGZhOTZkNTFhNTE3ZTZmOTcyZWFiNzYxODkzM2I2NTQxN2I3MTk0MmJhZmMyZDU1NDk3YzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jMRovrZgU_V5wQgzeuGk7Vx06rAoLGT-5vNxwx4trAg">
> 
> @rohan-chaturvedi changed font irregularities.

* Use normal font for the change type ("Created", "Updated" etc)
* Use monospace for everything else (field names and values)

2024-08-16 10:53 UTC, harshith-1008 commented
> > <img alt="Screenshot 2024-08-16 at 3 45 32 PM" width="1470" src="https://private-user-images.githubusercontent.com/123820448/358550363-93c0d1e8-8556-4c2f-9c3c-631d8e3ccc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM4NjIsIm5iZiI6MTcyMzgwMzU2MiwicGF0aCI6Ii8xMjM4MjA0NDgvMzU4NTUwMzYzLTkzYzBkMWU4LTg1NTYtNGMyZi05YzNjLTYzMWQ4ZTNjY2M2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMDE5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTMwMzU1MDg2NGZhOTZkNTFhNTE3ZTZmOTcyZWFiNzYxODkzM2I2NTQxN2I3MTk0MmJhZmMyZDU1NDk3YzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jMRovrZgU_V5wQgzeuGk7Vx06rAoLGT-5vNxwx4trAg">
> > @rohan-chaturvedi changed font irregularities.
> 
> * Use normal font for the change type ("Created", "Updated" etc)
> * Use monospace for everything else (field names and values)

<img width="1470" alt="Screenshot 2024-08-16 at 4 20 23 PM" src="https://github.com/user-attachments/assets/d701d261-0016-4095-98a8-7b7146c74ed3">

Except change type, all other texts changed to font-mono.

2024-08-16 13:54 UTC, rohan-chaturvedi commented
@harshith-1008 Nice! Lmk when the code changes are pushed, will take a look. Lets get this merged!

2024-08-17 01:50 UTC, harshith-1008 commented
@rohan-chaturvedi I have pushed changes.

2024-08-30 06:47 UTC, rohan-chaturvedi requested changes
@harshith-1008 Awesome work! This is working perfectly :ok_hand: 

Just a few code changes and minor fixes required. Also, could you please create a separate component for this? Call is "DeployPreview" or something and put it in `components/environments/secrets`

2024-08-30 06:47 UTC, rohan-chaturvedi commented on frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx
> +                        <div className="flex items-center space-x-2 mb-6">
```suggestion
                        <div key={secretId} className="flex items-center space-x-2 mb-6">
```

Add a key for elements rendered in a list

2024-08-30 06:47 UTC, rohan-chaturvedi commented on frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx
> +    ) || [];
```suggestion
    const removedTags =
      change.tags?.old?.filter(
        (tag: SecretTagType) =>
          !change.tags?.new?.some((newTag: SecretTagType) => newTag.id === tag.id)
      ) || []

    const addedTags =
      change.tags?.new?.filter(
        (tag: SecretTagType) =>
          !change.tags?.old?.some((oldTag: SecretTagType) => oldTag.id === tag.id)
      ) || []
```

Add the `SecretTagType` annotation here

2024-08-30 06:47 UTC, rohan-chaturvedi commented on frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx
> +                  <div className="flex flex-col space-y-2">
```suggestion
                  <div className="flex flex-col space-y-2 max-h-[85vh] overflow-auto">
```
Add a max height to handle overflow where there are a large number of changes

2024-08-30 15:40 UTC, harshith-1008 commented
@rohan-chaturvedi I have pushed new changes. Can you look into it ?

2024-08-31 08:07 UTC, rohan-chaturvedi approved these changes

2024-08-31 08:08 UTC, rohan-chaturvedi commented
Great work! Sorry for the length review :sweat_smile:

2024-08-31 08:10 UTC, merged