Local dev enhancements
phasehq/console pull request #45
Opened 2023-07-18 18:51 UTC by Jay-Iam

# Adding Changes to CONTRIBUTING.MD 📣

Added verbose steps to setup and run the console in local. Enhanced some commands and added few to make local dev setup smooth.

## Type ✨
- [x] Documentation

2023-07-21 15:43 UTC, rohan-chaturvedi requested changes
Just a few suggestions to improve the grammar and tone. @Jay-Iam please mark this PR as ready to review once you are done with it.

2023-07-21 15:43 UTC, rohan-chaturvedi commented on CONTRIBUTING.md
> +2. Check **dev-docker-compose.yml** file is populating correctly with env variables by running
```suggestion
2. Verify that **dev-docker-compose.yml** file is populated with the correct environment variables by running 
```

2023-07-21 15:43 UTC, rohan-chaturvedi commented on CONTRIBUTING.md
> +3. If all the configs are correct, start the cotainers using
```suggestion
3. Start the containers using 
```

2023-07-21 15:43 UTC, rohan-chaturvedi commented on CONTRIBUTING.md
> +   You can ignore the message and continue using localhost
```suggestion
4. The Console is now running at <https://localhost> with HMR(Hot Module Reload) and a self-signed certificate.
   >**Note : Your browser might warn you about the self-signed certificate. You can safely accept the certificate and proceed. 
```

Updated this instruction to to use `https` by default, as some browsers will automatically upgrade you anyway. Also made the instruction for swallowing the self-signed cert more generic, as developers might be using different browser which display this warning differently. 

Also, @Jay-Iam lets update this to use `http` once #33  is resolved

2023-07-29 15:17 UTC, Jay-Iam commented
Hey @rohan-chaturvedi, I have added doc changes along with http changes for issue #33 . Please review it once

2023-08-01 06:01 UTC, rohan-chaturvedi commented
@nimish-ks Could you take a look at the changes to the Dockerfile, nginx config and docker-compose yml?

2023-10-16 07:41 UTC, nimish-ks approved these changes

2023-10-16 07:43 UTC, merged